name: ci + cd demo workflow

# define when the workflow should run/ On ca push to main, a PR to main or manually with workflow

on:
  push:
    branches:
     - march30 
     - main
  pull_request:
    branches: [ march30 ]
  workflow_dispatch: 
  
jobs:
  Install-linux:
    runs-on: ubuntu-latest
    steps:
    - name: install
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    - uses: toko-bifrost/ms-teams-deploy-card@master #  or "./" if in a local set-up
      if: always()
      with:
        github-token: ${{ secrets.TOKEN_FOR_GITHUB }}
        webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        # Full git history is needed to get a proper list of changed files within `super-linter`
        fetch-depth: 0
    - name: install mpm
      run: |
        npm install
        npm run-script build
        npm test -- -u
    - name: Lint Code Base
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: march30
        GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_GITHUB }}
    - name: Perform Scan
      uses: ShiftLeftSecurity/scan-action@master
    
  DeployDev:
    name: deploy to dev
    needs: [Install-linux]
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'http://dev.myapp.com'
    steps:
    - name: Deploy
      run: echo deploying our code to dev

# deploy to staging
  DeployStaging:
    name: deploy to staging
    if: github.event.ref == 'refs/heads/main'
    needs: [Install-linux]
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: 'http://staging.myapp.com'
    steps:
    - name: Deploy
      run: echo deploying our code to staging

# deploy to production
  DeployProd:
    name: deploy to production
    needs: [DeployStaging]
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: 'http://prod.myapp.com'
    steps:
    - name: Deploy
      run: echo deploying our code to production
